### ISSUE TITLE
Navbar item select scroll

### ISSUE THREAD

**Issue by aviiciii** [rosalie0/rosalie0.github.io#79]
Hi, I really liked your portfolio and I have come across a bug in your portfolio website and wanted to inform you about it. 

When using the navbar items to smoothly scroll down to a specific section, I noticed that the section is not aligned correctly at the top. This causes the bottom part of the previous section to remain visible, creating a visual glitch. I have attached some images for reference.

- projects
![image](https://github.com/rosalie0/rosalie0.github.io/assets/88141521/0bc41a0c-7e88-43cb-8dc6-b828132b1957)

- contact
<img width="1512" alt="image" src="https://github.com/rosalie0/rosalie0.github.io/assets/88141521/b3aef815-61bd-47c8-bb82-35503d4e0b35">

**Comment by rosalie0** [comment]
Hey - thank you so much for noticing this!
This is happening because I actually adjusted the place where the the link scrolls 'to' because the navbar is supposed to be fixed to the viewport at the top, and that 'extra' height is actually exactly the height of the navbar.

The problem is that at some point my fixed navbar no longer became fixed.

Thank you for pointing this out!
